name: 'Setup LunaSec Docker Containers'
description: 'Creates and builds the LunaSec Docker containers'

#outputs:
#  :
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    # Cancel the merge copy of this build(see the matrix above) if we are not in a PR
#    - name: cancelling
#      uses: andymckay/cancel-action@0.2
#      if: ${{ steps.job-canceller.outputs.cancelled == 'true' }}

  - name: Set up Docker BuildKit
    id: buildx
    uses: docker/setup-buildx-action@v1
    with:
      install: true # sets buildx as the default for docker, which should apply to docker-compose commands
      driver: docker

  - uses: actions/setup-node@v2
    with:
      node-version: '14'
      cache: yarn

  # specifically tag this bootstrap container to prevent rebuilds
  - name: Build Lerna Bootstrap container
    env:
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    run: docker build --progress plain -f ./js/docker/demo.dockerfile -t lerna-bootstrap --target lerna-bootstrap .

  - name: Build CLI Container
    env:
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    run: docker build --progress plain -f ./js/docker/demo.dockerfile -t repo_lunasec-cli --target lunasec-cli .
