# CHANGES IN THIS FOLDER WILL ONLY TAKE PLACE ONCE YARN INSTALL HAS BEEN RE-RUN, which regenerates the .pnp.cjs file
cacheFolder: ./.yarn/cache

# This option can be used to control hoisting, I think we may want to consider setting it to "workspaces" if any hoisting issues come up.
nmHoistingLimits: none
nodeLinker: pnp

# Only needed for Docusaurus to work. We should remove this when we are able to!
pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  # Necessary for Webpack to be happy and function for bundling
  stream-http@*:
    peerDependencies:
      url: "*"
  readable-stream@*:
    dependencies:
      events: "*"
  https-browserify@*:
    peerDependencies:
      url: "*"
  promise-inflight@*:
    dependencies:
      bluebird: "^3.7.2"
  react-scripts@*:
    peerDependencies:
      "@types/node": "*"
      "@types/react-dom": "*"
  "@types/node@^14.0.0":
    peerDependencies:
      events: "*"
      util: "*"
      url: "*"
      querystring: "*"

  # Other deps
  express-openapi-validator@*:
    dependencies:
      express: "*"
  aws-cdk-local@1.65.8:
    dependencies:
      aws-cdk: "1.129.0"
      cdk-assets: "1.129.0"
  styled-components@^5.3.3:
    dependencies:
      react-is: "*"
  redoc@*:
    dependencies:
      call-me-maybe: "^1.0.1"
      yaml: "^1.10.2"
      fast-safe-stringify: "^2.1.1"
  node-fetch@^2.6.1:
    dependencies:
      encoding: "^0.1.12"
  "@docusaurus/theme-search-algolia@2.0.0-beta.ff31de0ff":
    dependencies:
      prism-react-renderer: "^1.2.1"
  "@docsearch/react@3.0.0-alpha.41":
    dependencies:
      "@algolia/client-search": "^4.11.0"
  debug@*:
    dependencies:
      supports-color: "*"
  "@material-ui/lab@^4.12.3":
    dependencies:
      "@material-ui/types": "^5.1.0"

