cacheFolder: ./.yarn/cache

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  # Necessary for Webpack to be happy and function for the Secure Frame
  stream-http@*:
    peerDependencies:
      url: "*"
  readable-stream@*:
    dependencies:
      events: "*"
  https-browserify@*:
    peerDependencies:
      url: "*"
  express-openapi-validator@*:
    dependencies:
      express: "*"
  aws-cdk-local@1.65.8:
    dependencies:
      aws-cdk: "1.129.0"
      cdk-assets: "1.129.0"
