name: 'Setup Docker CI Environment'
description: 'Creates the LunaSec CI build environment'
  merge-master:
    description: 'If true, this merges the master branch during setup.'
    required: true
    default: false
  skip-docker:
    description: 'If true, skips the Docker install step'
    required: false
    default: false
#outputs:
#  :
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  env:
    # avoid warnings like "tput: No value for $TERM and no -T specified"
    TERM: xterm
  steps:
    #TODO: there may be a more idiomatic way to do this
    - name: Check if we should skip this build
      id: job-canceller
      run: echo "::set-output name=cancelled::${{ inputs.merge-master == true && github.event_name != 'pull_request'}}"

    # Cancel the merge copy of this build(see the matrix above) if we are not in a PR
    - name: cancelling
      uses: andymckay/cancel-action@0.2
      if: ${{ steps.job-canceller.outputs.cancelled == 'true' }}

      # merge with master(or whatever target branch) so we are actually testing what will happen after PR merges, not just this branch
    - name: Merge target branch
      run: git merge origin/${{ github.event.pull_request.base.ref }}
      if: ${{ inputs.merge-master == true && github.event_name == 'pull_request' }}

    - name: Setup Docker Containers
      uses: ./.github/actions/setup-lunasec-containers@v1
      if: ${{ inputs.skip-docker != false }}
