name: Check Dependencies

# This workflow checks to make sure that all dependency binaries are valid, to prevent a sneaky commit doing something malicious
on:
  pull_request:
    branches: ['**', '**']
  push:
    branches: [master]

jobs:
  check-deps:
    runs-on: ubuntu-latest
    env:
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
      RUNNING_IN_CI: true
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    strategy:
      matrix:
        merge: ["merged", "not-merged"]
        lockfile: ["lockfile"] #,"no-lockfile"]
        exclude:
          - merge: "merged"
            lockfile: "no-lockfile"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: yarn

    - name: dependencies
      env:
        IS_LUNASEC_CI: true
      run: yarn install --immutable --immutable-cache --check-cache --inline-builds
